# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftDemo-LoginAnimation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftDemo-LoginAnimation

  pod 'SnapKit' , '~>5.0.0'

  pod 'Kingfisher'
  
  target 'SwiftDemo-LoginAnimationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
